version: "3.4"

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        volumes:
            - ./prometheus:/etc/prometheus
            - prometheus_data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        ports:
            - "9090:9090"

    # Chỉ lấy thông tin trong Linus OS
    # node-exporter:
    #     image: prom/node-exporter:latest
    #     ports:
    #     - "9100:9100"
        
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        volumes:
            - grafana_data:/var/lib/grafana
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_USERS_ALLOW_SIGN_UP=false
            - GF_SMTP_ENABLED=true
            - GF_SMTP_HOST=smtp.gmail.com:587
            - GF_STMTP_USER=hvnet.tagsmanager@gmail.com
            - GF_SMTP_PASSWORD=HVNet@114
            - GF_SMTP_SKIP_VERIFY=true
            - GF_SMTP_FROM_ADDRESS=hvnet.tagsmanager@gmail.com
            - GF_RENDERING_SERVER_URL=http://render:8001/render
            - GF_RENDERING_CALLBACK_URL=http://grafana:3000
            - GF_LOG_FILTERS= rendering:debug
        restart: unless-stopped
        ports:
            - "3000:3000"
        depends_on:
            - prometheus            

    renderer:
        image: grafana/grafana-image-renderer:latest
        ports:
            - "8081:8081"
        environment:
            - ENABLE_METRICS= 'true'            
      