global:
  scrape_interval:      5s
  evaluation_interval:  5s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
rule_files:

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s  
    static_configs:
      - targets: ['192.168.1.113:9090']
  - job_name: 'node-exporter'
    scrape_interval: 5s    
    static_configs:
        - targets: ['192.168.1.113:9100']
  # - job_name: 'cadvisor'
  #   scrape_interval: 5s
  #   static_configs:
  #       - targets: ['192.168.1.113:8080']              