global:
  scrape_interval:      5s
  evaluation_interval:  5s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
rule_files:

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s  
    static_configs:
      - targets: ['192.168.1.113:9090','192.168.1.104:9182']